name = "liga-nexo-api"
main = "api/index.js"
compatibility_date = "2023-01-23"

[site]
bucket = "./assets"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "liga-nexo-api.liga-nexo.workers.dev" }
]