name: Scrape Liga Nexo teams

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "0 */1 * * 3"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrape:teams
          git config --global user.name anietoan455
          git config --global user.email "angel.angulo.pam@gmail.com"
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update Liga Nexo bbdd"
          git push origin main
