name: Scrape Liga Nexo leaderboard

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "0 4 * * 2"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrape:leaderboard
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT_AUTO_PR }}
          commit-message: Update liga Nexo leaderboard bbdd
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: develop
          base: main
          delete-branch: false
          title: "[Scrapper] Update leaderboard"
          body: |
            Update Leaderboard bbdd
            - Updated leaderboard.json bbdd
          labels: |
            scrapping
            automated pr
          assignees: kaixe455
          reviewers: kaixe455
          team-reviewers: |
            owners
          draft: false
